
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Button button1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.Label label5;

	private global::Gtk.RadioButton radiobutton1;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.CheckButton checkbutton3;

	private global::Gtk.RadioButton radiobutton2;

	private global::Gtk.CheckButton checkbutton4;

	private global::Gtk.Entry entry1;

	private global::Gtk.Label label6;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Button button2;

	private global::Gtk.Entry entry2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.WidthRequest = 22;
		this.fixed1.HeightRequest = 88;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Cotizador Express");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w1.X = 177;
		w1.Y = 3;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Tienda:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w2.X = 3;
		w2.Y = 20;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w3.X = 313;
		w3.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Vendedor - Codigo");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w4.X = 4;
		w4.Y = 48;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Historial");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w5.X = 313;
		w5.Y = 42;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.fixed1.Add(this.hseparator1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
		w6.X = -23;
		w6.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.WidthRequest = 450;
		this.hseparator2.HeightRequest = 6;
		this.hseparator2.Name = "hseparator2";
		this.fixed1.Add(this.hseparator2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator2]));
		w7.X = 8;
		w7.Y = 81;
		this.vbox1.Add(this.fixed1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.WidthRequest = 4;
		this.fixed2.HeightRequest = 125;
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Prenda");
		this.fixed2.Add(this.label5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
		w9.X = 195;
		w9.Y = 5;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Camisa"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed2.Add(this.radiobutton1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton1]));
		w10.X = 13;
		w10.Y = 23;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Manga Corta");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed2.Add(this.checkbutton1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton1]));
		w11.X = 139;
		w11.Y = 25;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString("Cuello Mao");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed2.Add(this.checkbutton2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton2]));
		w12.X = 275;
		w12.Y = 26;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton3 = new global::Gtk.CheckButton();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Chupin");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.fixed2.Add(this.checkbutton3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton3]));
		w13.X = 138;
		w13.Y = 55;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Pantalon"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.fixed2.Add(this.radiobutton2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radiobutton2]));
		w14.X = 10;
		w14.Y = 54;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton4 = new global::Gtk.CheckButton();
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString("Premium");
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.fixed2.Add(this.checkbutton4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton4]));
		w15.X = 68;
		w15.Y = 86;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 100;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed2.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry1]));
		w16.X = 323;
		w16.Y = 82;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Cant. :");
		this.fixed2.Add(this.label6);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w17.X = 280;
		w17.Y = 85;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.WidthRequest = 461;
		this.hseparator3.HeightRequest = 6;
		this.hseparator3.Name = "hseparator3";
		this.fixed2.Add(this.hseparator3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.hseparator3]));
		w18.X = 12;
		w18.Y = 113;
		this.vbox1.Add(this.fixed2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed2]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.WidthRequest = 19;
		this.fixed3.HeightRequest = 78;
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 140;
		this.button2.HeightRequest = 50;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Cotizar");
		this.fixed3.Add(this.button2);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button2]));
		w20.X = 29;
		w20.Y = 8;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString("Resultado.");
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.fixed3.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry2]));
		w21.X = 192;
		w21.Y = 18;
		this.vbox1.Add(this.fixed3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed3]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 437;
		this.DefaultHeight = 303;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.click2);
		this.button2.Clicked += new global::System.EventHandler(this.Click);
	}
}
